### ISSUE TITLE
CRUD operation after Search

### ISSUE THREAD

**Issue by mxchai** [cs2103jan2015-w15-1j/main#47]
Need to resolve how we are going to implement Delete and Edit after the user has used the Search function.

For example, if Search brings up a list of result, each numbered, then how is Delete <int> going to interact with the display list of items? Currently, the behaviour is counter-intuitive; delete <int> deletes the task associated with <int> in the Display function, not of the Search function.

**Comment by Muhammad-Adam** [comment]
Done, nuff said
