### ISSUE TITLE
Display should be able to show completed or not completed tasks

### ISSUE THREAD

**Issue by Ck91** [cs2103jan2015-w15-1j/main#52]
default: Not Completed

**Comment by Ck91** [comment]
Layout:
Floating
dated deadline (nearest to oldest)
timed deadline (nearest to oldest)

**Comment by Muhammad-Adam** [comment]
Our implementation now will show only incomplete tasks. In order to show completed tasks, user have to type some commands, correct? If that is the case, can close issue already. Thanks.
