### ISSUE TITLE
Adding tasks with numbers causes DateParser to use it incorrectly

### ISSUE THREAD

**Issue by sebastianquek** [cs2103jan2015-w15-1j/main#59]
Examples:
"add do assignment 2 by friday" creates a task with description "do assignment" and incorrect date.
"add create 20 word poem" creates a task with description "create word poem" with a date when it should be floating.

**Comment by sebastianquek** [comment]
Currently fixed, have to monitor if anymore similar bugs are found.

**Comment by sebastianquek** [comment]
"add attend meeting 23 march 1200 - 1400" doesn't work as expected.

**Comment by sebastianquek** [comment]
Command: add attend meeting 23 march 1200 - 1400
Task has been successfully added:
     Description: attend meeting 1200 - 1400
     Deadline: 2015-03-23
     Time: Not applicable

After the edits, it shows the correct date but does not register the input timing.

**Comment by Muhammad-Adam** [comment]
Is this still an issue @sebastianquek ?

**Comment by sebastianquek** [comment]
So far there hasn't been anymore outstanding issues. Will close this.
