### ISSUE TITLE
Make completeTask work with GUI

### ISSUE THREAD

**Issue by mxchai** [cs2103jan2015-w15-1j/main#69]

**Comment by Muhammad-Adam** [comment]
Works.. nuff said

**Comment by sebastianquek** [comment]
Does not work with the checkbox next to each task.

**Comment by Muhammad-Adam** [comment]
It works when the person type the command "complete".

**Comment by sebastianquek** [comment]
Checkboxes now work as expected. 3bb447ca8371e98a2ad2f9b095c7d5991e8ad59c
