### ISSUE TITLE
Revamp GUI layout

### ISSUE THREAD

**Issue by mxchai** [cs2103jan2015-w15-1j/main#72]

**Comment by sebastianquek** [comment]
GUI doesn't use a table anymore. Will update the interface as we progress.

**Comment by sebastianquek** [comment]
GUI doesn't show timed tasks properly.

**Comment by Muhammad-Adam** [comment]
It does la...walao

**Comment by sebastianquek** [comment]
LOL, that comment was before you added it in.

**Comment by mxchai** [comment]
Eh you all think this is Facebook ah
