### ISSUE TITLE
Fix DateParser invalid inputs

### ISSUE THREAD

**Issue by sebastianquek** [cs2103jan2015-w15-1j/main#82]
DateParser does not parse these inputs properly:
* add fries
* add do homework from 12.00 to 14.00

**Comment by sebastianquek** [comment]
"add fries" works properly.
"add do homework from 12.00 to 14.00" will not be fixed. 

DateParser parses "12.00 to 14.00" and creates a timed-task as expected but the description still shows "12.00 to 14.00". This is because Natty parses "1200 to 1400" with the periods removed. 

The fix will likely be very complex and we do not have the time to fix this minor issue.

**Comment by sebastianquek** [comment]
@Muhammad-Adam thought of a brilliant idea to replace the periods with colons before parsing. This ensures that Natty parses "12:00 to 14:00". The way descriptions are generated in the task class has been modified to depend on DateParser for the non-parsed words instead.

**Comment by Muhammad-Adam** [comment]
Thanks
